# Generated by Django 2.2.13 on 2022-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0070_auto_20221019_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
