# Generated by Django 2.2.13 on 2022-11-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0072_auto_20221124_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmain',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
